name: Dropwizard Swagger CI

on:
  push:
    - master

  pull_request:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-uidist-{{ hashFiles('src/main/resources/static/swagger-ui/*.*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Clone Swagger UI distro
        run: ${GITHUB_WORKSPACE}/update-swagger-ui.sh

      - name: Build
        run: ./gradlew build
